ignore:
  - vulnerability: CVE-2024-5535
    package:
      name: libssl3
      version: 3.3.1-r0

  - vulnerability: CVE-2024-5535
    package:
      name: libcrypto3
      version: 3.3.1-r0
      
  - vulnerability: CVE-2023-45853
    package:
      name: zlib
      version: 1.3.1-r2